# Generated by Django 3.2.7 on 2021-09-19 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hikebooker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='hike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hikebooker.hike'),
        ),
    ]
